export const contentCSFNext = [
  {
    language: 'js',
    renderer: 'react',
    tabTitle: 'CSF 3',
    raw: 'console.log(process.env.STORYBOOK_THEME);\nconsole.log(process.env.STORYBOOK_DATA_KEY);',
    content:
      '<figure data-rehype-pretty-code-figure=""><pre class="Firefox Light" style="--shiki-dark:#abb2bf;--shiki-light:#939393;--shiki-dark-bg:#0F172A;--shiki-light-bg:#FFFFFF" tabindex="0" data-language="js" data-theme="one-dark-pro Firefox Light"><code data-language="js" data-theme="one-dark-pro Firefox Light" style="display: grid;"><span data-line=""><span style="--shiki-dark:#E5C07B;--shiki-light:#8000D7">console</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">.</span><span style="--shiki-dark:#61AFEF;--shiki-light:#058B00;--shiki-dark-font-style:inherit;--shiki-light-font-style:italic">log</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">(</span><span style="--shiki-dark:#E5C07B;--shiki-light:#8000D7">process</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">.</span><span style="--shiki-dark:#E5C07B;--shiki-light:#058B00">env</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">.</span><span style="--shiki-dark:#E06C75;--shiki-light:#058B00">STORYBOOK_THEME</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">)</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#939393">;</span></span>\n<span data-line=""><span style="--shiki-dark:#E5C07B;--shiki-light:#8000D7">console</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">.</span><span style="--shiki-dark:#61AFEF;--shiki-light:#058B00;--shiki-dark-font-style:inherit;--shiki-light-font-style:italic">log</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">(</span><span style="--shiki-dark:#E5C07B;--shiki-light:#8000D7">process</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">.</span><span style="--shiki-dark:#E5C07B;--shiki-light:#058B00">env</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">.</span><span style="--shiki-dark:#E06C75;--shiki-light:#058B00">STORYBOOK_DATA_KEY</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">)</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#939393">;</span></span></code></pre></figure>',
  },
  {
    language: 'js',
    renderer: 'react',
    tabTitle: 'CSF Next 🧪',
    raw: 'console.log(import.meta.env.STORYBOOK_THEME);\nconsole.log(import.meta.env.STORYBOOK_DATA_KEY);',
    content:
      '<figure data-rehype-pretty-code-figure=""><pre class="Firefox Light" style="--shiki-dark:#abb2bf;--shiki-light:#939393;--shiki-dark-bg:#0F172A;--shiki-light-bg:#FFFFFF" tabindex="0" data-language="js" data-theme="one-dark-pro Firefox Light"><code data-language="js" data-theme="one-dark-pro Firefox Light" style="display: grid;"><span data-line=""><span style="--shiki-dark:#E5C07B;--shiki-light:#8000D7">console</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">.</span><span style="--shiki-dark:#61AFEF;--shiki-light:#058B00;--shiki-dark-font-style:inherit;--shiki-light-font-style:italic">log</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">(</span><span style="--shiki-dark:#C678DD;--shiki-light:#DD00A9">import</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">.</span><span style="--shiki-dark:#E06C75;--shiki-light:#939393">meta</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">.</span><span style="--shiki-dark:#E5C07B;--shiki-light:#058B00">env</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">.</span><span style="--shiki-dark:#E06C75;--shiki-light:#058B00">STORYBOOK_THEME</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">)</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#939393">;</span></span>\n<span data-line=""><span style="--shiki-dark:#E5C07B;--shiki-light:#8000D7">console</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">.</span><span style="--shiki-dark:#61AFEF;--shiki-light:#058B00;--shiki-dark-font-style:inherit;--shiki-light-font-style:italic">log</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">(</span><span style="--shiki-dark:#C678DD;--shiki-light:#DD00A9">import</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">.</span><span style="--shiki-dark:#E06C75;--shiki-light:#939393">meta</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">.</span><span style="--shiki-dark:#E5C07B;--shiki-light:#058B00">env</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">.</span><span style="--shiki-dark:#E06C75;--shiki-light:#058B00">STORYBOOK_DATA_KEY</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#4A4A4F">)</span><span style="--shiki-dark:#ABB2BF;--shiki-light:#939393">;</span></span></code></pre></figure>',
  },
];
