import { Footer } from "@/components/footer/footer";
import { Header } from "@/components/header/header";

export default function Home() {
  return (
    <>
      <Header variant="home" />
      <main className="max-w-8xl mx-auto px-4 lg:px-8 py-12 bg-zinc-900 text-white">
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
      </main>
      <Footer variant="home" />
    </>
  );
}
