import { Footer } from "@/components/footer/footer";
import { Header } from "@/components/header/header";
import { Fragment } from "react";

export default function Home() {
  return (
    <Fragment>
      <Header variant="home" />
      <main className="max-w-8xl mx-auto px-4 lg:px-8 py-12">
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
        <div>Hello Home</div>
      </main>
      <Footer variant="home" />
    </Fragment>
  );
}
